[build]
command = "npm run build"
functions = "functions"
publish = "build"

[template.environment]
  ASTRA_DB_USERNAME = "Your Astra DB Username"
  ASTRA_DB_PASSWORD = "Your Astra DB Password"
  ASTRA_DB_KEYSPACE = "Your Astra DB Keyspace"
  ASTRA_DB_REGION = "Your Astra DB Region"
  ASTRA_DB_ID = "Your Astra DB ID"
  
[build.environment]
  ASTRA_DB_USERNAME = "TESTME"
  
[context.production]
  ASTRA_DB_USERNAME = "TESTME"
  environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "14.15.3" }
